### ISSUE TITLE
Combine Sprockets with Node

### ISSUE THREAD

**Issue by kareemk** [erithmetic/nodeify#3]
Any ideas on easy ways to extend this project to combine sprockets with Node so that node modules can be included and used in a Rails app but the javascript in the Rails app still uses Sprockets to manage javascript?

**Comment by erithmetic** [comment]
@joefiorini and I were looking at this but after some thought I realized the Common.js module style that npm uses is incompatible with Sprockets' view of "require." In the Common.js world, the require function returns a value that is a reference to the included module:

```
// in mylib.js
module.exports.run = function(input) { ... };

// in application.js
var mylib = require('mylib');
mylib.run('something');
```

In the world of Sprockets, any call to require simply inserts the content of the required file into the main file. It assumes that anything declared in the module is available in the global context.

```
// in mylib.js
function run(input) { ... };

// in application.js
// require mylib
run('something');
```

It really doesn't make sense to me to try and reconcile these two ideas. I see nodeify as a complete replacement of Sprockets.

**Comment by erithmetic** [comment]
Well, it turns out I was wrong!

I found myself in a position where I needed the rails-ujs/jquery-rails helpers so I hammered out a way to combine sprockets and nodeify! This functionality is now in v0.0.6.

**Comment by erithmetic** [comment]
Eventually, I'd like to have a CommonJS implementation of UJS but this will suffice until that happens.
